services:
  - type: web
    name: likhub2
    env: node
    buildCommand: >
      cd frontend && 
      npm install && 
      npm run build && 
      ls -la build && 
      ls -la build/static && 
      cat build/index.html | head -20
    startCommand: cd frontend && npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: web
    name: likhub-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false 